### ISSUE TITLE
Please publish changelogs

### ISSUE THREAD

**Issue by tremby** [etchteam/storybook-addon-marker#11]
Updating was a pain just now -- without a changelog or upgrade guide, it took sleuthing to figure out that I no longer need to add a decorator to storybook in the preview file.

**Comment by DanWebb** [comment]
@tremby Sorry to hear that.

The decorators isn't mentioned [in the readme](https://github.com/etchteam/storybook-addon-marker?tab=readme-ov-file#configuration) anymore and changelogs will be published from [v4.0.0](https://github.com/etchteam/storybook-addon-marker/releases/tag/v4.0.0) onwards using the semantic release

**Comment by tremby** [comment]
> The decorators isn't mentioned [in the readme](https://github.com/etchteam/storybook-addon-marker?tab=readme-ov-file#configuration) anymore

Sure, but diffing the readme vs an older one is not my first instinct. Not a bad idea, maybe I'll think of it next time I'm in this situation. But the fact is that I simply did not at all remember the setup procedure I went through months ago for the older version, so didn't even remember that decorator existed.

> changelogs will be published from [v4.0.0](https://github.com/etchteam/storybook-addon-marker/releases/tag/v4.0.0) onwards using the semantic release

Great.
